name: Semantic Release -- package.json version bump

on:
  push:
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: lib
        run: npm install
      
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: cycjimmy/semantic-release-action@v4
        with:
          # Change the working directory to the 'lib' subdirectory
          working_directory: lib